authors = ["EwDev (https://ewdev.net/)"]
description = "Polyfills for TypeScriptToLua"
includes = [
    "src/**/*",
    "pesde.toml",
    "LICENSE",
]
license = "MIT"
name = "jsdotluau/tstl_polyfill_lune"
private = true
repository = "https://github.com/jsdotluau/tstl_polyfill"
version = "1.33.0-rc.2"
workspace_members = ["dist/*"]

[dependencies.pathfs]
name = "jiwonz/pathfs"
version = "^0.6.0"

[engines]
lune = "^0.10.4"
pesde = "^0.7.1"

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
build = ".lune/build.luau"
fetchUpstream = ".lune/fetchUpstream.luau"
install = ".lune/install.luau"

[target]
environment = "lune"
lib = "src/init.luau"
