authors = ["EwDev (https://ewdev.net/)"]
description = "Polyfills from TypeScriptToLua"
includes = ["src/**/*", "pesde.toml", "LICENSE"]
license = "MIT"
name = "jsdotluau/tstl_polyfill_lune"
private = true
repository = "https://github.com/jsdotluau/polyfill"
version = "1.33.0"
workspace_members = ["dist/*"]

[dependencies.pathfs]
name = "jiwonz/pathfs"
version = "^0.6.0"

[engines]
lune = "^0.10.4"
pesde = "^0.7.1"

[indices]
default = "https://github.com/pesde-pkg/index"

[scripts]
build = ".lune/build.luau"
install = ".lune/install.luau"
updateSubmodules = ".lune/updateSubmodules.luau"

[target]
environment = "lune"
lib = "src/init.luau"
