name = "jsdotluau/tstl_polyfill_lune"
version = "0.1.0"
description = "Polyfills from TypeScriptToLua"
authors = ["EwDev (https://ewdev.net/)"]
repository = "https://github.com/jsdotluau/polyfill"
license = "MIT"
includes = ["src/**/*", "pesde.toml", "LICENSE"]
private = true

workspace_members = ["dist/*"]

[engines]
pesde = "^0.7.1"
lune = "^0.10.4"

[target]
environment = "lune"
lib = "src/init.luau"

[scripts]
install = ".lune/install.luau"
build = ".lune/build.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[dependencies]
pathfs = { name = "jiwonz/pathfs", version = "^0.6.0" }
